# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Ensure the .NET SDK is available
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  
- powershell: |
    $config = @"
    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
        <clear />
        <add key="Lab4_feed" value="https://pkgs.dev.azure.com/slovecch/Lab4Question1/_packaging/Lab4_feed/nuget/v3/index.json" />
      </packageSources>
    </configuration>
    "@
    $config | Out-File -FilePath "$(Agent.BuildDirectory)/NuGet.Config" -Encoding UTF8
  displayName: 'Write NuGet.config inline'

# Restore dependencies
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    arguments: '--configfile $(Agent.BuildDirectory)/NuGet.Config'

# Build the solution
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration Release'

# Push NuGet package to Azure Artifacts
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    arguments: '--configfile $(Agent.BuildDirectory)/NuGet.Config --verbosity detailed  --source https://pkgs.dev.azure.com/slovecch/Lab4Question1/_packaging/Lab4_feed/nuget/v3/index.json'


   


