# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Ensure the .NET SDK is available
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  

# Restore dependencies
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'

# Build the solution
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

# Pack the NuGet package
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    arguments: '--configfile $(Agent.BuildDirectory)/NuGet.Config'




#Push the NuGet package to Azure Artifacts
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    arguments: '--configfile $(Agent.BuildDirectory)/NuGet.Config --verbosity detailed --source https://pkgs.dev.azure.com/slovecch/Lab4Question1/_packaging/Lab4_feed/nuget/v3/index.json'


   


